@startuml logical-data-model
' Some whitespace characters (` `) are set to allow enough space
' See https://github.com/plantuml/backlog/issues/11

skinparam linetype ortho
skinparam nodesep 200

title Logical Data Model for Mini Social Network

entity User {
  * id [PK]
  --
  * firstName
  * lastName
  * username
  * email
  * password
  created_at
  updated_at
}

entity Post {
  * id [PK]
  --
  * user_id [FK]
  title
  * content
  created_at
  updated_at
}

entity Like {
  * user_id [PK, FK]
  * post_id [PK, FK]
  --
  reaction
}

User "1 " --- "0..*" Post : creates 
User "1 " --- "0..*" Like : likes 
Post "1 " --- "0..*" Like : is liked by 

legend right
Legend
| **Symbol** | **Meaning** |
| E | Entity |
| 1 | Exactly one |
| 0..1 | Zero or one |
| 1..* | One or many |
| 0..* | Zero or many |
| PK | Primary Key |
| FK | Foreign Key |
| Dot (●)| Mandatory field |
endlegend
@enduml
